- modules/LuneOS/Application/plugin/applicationwindow.cpp
- modules/LuneOS/Application/plugin/applicationwindow.h
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Add Pin window type and correct window id management

- README.md
> Add README.md for usage in desktop environment

- modules/LuneOS/Components/deployment.pri
Signed-off-by: Simon Busch <morphis@gravedo.de>
> Install missing page QML component

- modules/LuneOS/Components/deployment.pri
> Fix deployement for LuneOS.Components

- modules/LuneOS/Components/LunaWebEngineView.qml
> LunaWebEngineView: Enable some basic settings

- test/imports/LuneOS/Application/ApplicationWindow.qml
- test/imports/LuneOS/Application/Db8Model.qml
- test/imports/LuneOS/Application/qmldir
- test/imports/LuneOS/Service/LunaService.qml
*Migrate phone-app specifics to luneos-components
*Allow both luna and palm prefixes in service calls
*Initial work for stub Preware feeds for FirstUse
> Various additions to luneos-components

- test/imports/Connman/TechnologyModel.qml
- test/imports/org/nemomobile/dbus/DBus.qml
- test/imports/org/nemomobile/dbus/DBusInterface.qml
- test/imports/org/nemomobile/dbus/qmldir
> Add stub org.nemomobile.dbus module

- test/imports/LunaNext/Shell/DeviceKeyHandler.qml
> Update stub DeviceKeyHandler

- test/imports/LunaNext/Shell/GestureHandler.qml
- test/imports/LunaNext/Shell/qmldir
> LunaNext: Shell: Add stub GestureHandler

- modules/LuneOS/Components/ClippedImage.qml
> ClippedImage: avoid binding loops on height and width

- modules/LuneOS/Application/plugin/applicationwindow.h
- test/imports/LuneOS/Application/ApplicationWindow.qml
> Sync ApplicationWindow.WindowType with the ones from LunaNext

- test/imports/LuneOS/Application/Db8Model.qml
- test/imports/LuneOS/Application/db8content.js
* initiate the db kind with a json file
* query the db, sort it, filter is (simple queries only)
* add data to the db kind
> Db8Model: add more testing capabilities

- modules/LuneOS/Service/plugin/db8model.cpp
- modules/LuneOS/Service/plugin/db8model.h
- modules/LuneOS/Service/plugin/lunaserviceadapter.h
This avoid getting conflict with already defined subscriptions for the same app.
> Db8Model: use LunaServiceAdapter to get a LSHandle

- test/imports/LuneOS/Service/Db8Model.qml
- test/imports/LuneOS/Service/LunaService.qml
- test/imports/LuneOS/Service/db8content.js
> LuneOS.Service: improve Db8 stub

- modules/LuneOS/Service/plugin/db8model.cpp
- modules/LuneOS/Service/plugin/db8model.h
> Db8Model: restart db8 query if one of the properties has changed

- test/imports/LunaNext/Common/SettingsStub.js
> SettingsStub: add missing test platforms and properties

- modules/LuneOS/Telephony/libphonenumber-wrapper.js
> Telephony: use new geoLocation API from phonenumberlib

- modules/LuneOS/Components/LunaWebEngineView.qml
-Fullscreen support 
-Plugin support
> Enable features added by Qt 5.6

- modules/LuneOS/Components/Page.qml
- modules/LuneOS/Components/PageStackWindow.qml
- modules/LuneOS/Components/deployment.pri
- modules/LuneOS/Components/qmldir
Page.qml: Remove the anchors.rightMargin
PageStackWindow.qml: Added basic file used by FingerTerm.
> Add additional components for FingerTerm

- test/imports/LunaNext/Common/FileUtilsStub.js
- test/imports/LunaNext/Common/LedsAdapterStub.js
- test/imports/LunaNext/Common/qmldir
> Add stubs for FileUtils & Leds

- test/imports/LuneOS/Service/LunaService.qml
To fix errors while running in Qt Creator
> Add additional stub calls

- test/imports/LunaNext/Compositor/FakeWindows/DummyWindow.qml
> Use new luna://org.webosports.luna/enableFullScreenMode service

- test/imports/LuneOS/Service/LunaService.qml
> Add stub call for device info

- modules/LuneOS/Service/plugin/db8model.cpp
- modules/LuneOS/Service/plugin/db8model.h
> Db8Model: cancel running LS2 call upon destruction

- test/imports/LuneOS/Service/LunaService.qml
> Add proper results for com.palm.browserpreferences & region

- test/imports/LuneOS/Service/LunaService.qml
> Add stub values for db/merge, UniversalSearch & Browser Prefs

- test/imports/LunaNext/Shell/Notifications/NotificationManager.qml
> Test NotificationManager: add missing iconPath property to notif object

- test/imports/LuneOS/Service/LunaService.qml
> luneos-components: Return locale as well while subscribing

- test/imports/LuneOS/Service/LunaServiceRegistering.js
Seems we don't have all the apps we need to test it with LNC in
QtCreator, so adding them.
> Add missing apps to test data

- modules/LuneOS/Components/LunaWebEngineView.qml
> LunaWebEngineView: remove dependency on QtWebEngine.experimental

- modules/LuneOS/Components/UserAgent.qml
> UserAgent.qml: Update QtWebEngine & Chrome version

- modules/LuneOS/Components/js/ua-overrides.js
Update the UserAgent for web.whatsapp.com and add a ChomeOS ARM UserAgent for netflix.com
> ua-overrides.js

- modules/QtQuick/Controls.2/LuneOS/TextField.qml
> QtQuickControls2: TextField: lighter background

- modules/QtQuick/Controls.2/LuneOS/TextField.qml
> QtQuickControls2: TextField: Fix background

- test/imports/Connman/NetworkService.qml
This stub doesn't call the (stub) Connman agent like it should.
> Connman stub: fake connection

- test/imports/LuneOS/Service/LunaService.qml
* luna://com.palm.connectionmanager/getinfo
* palm://org.webosports.service.update/retrieveVersion
* palm://com.android.properties/getProperty
> LunaService stub: add some minor stub calls

- modules/QtQuick/Controls.2/LuneOS/qmldir
> QtQuickControls2: Add missing components to qmldir

- modules/LuneOS/Components/UserAgent.qml
There's no way around hardcoding the values it seems for now.
> UserAgent.qml: Update UserAgent for Qt 5.11.3

- modules/LuneOS/Components/UserAgent.qml
> UserAgent.qml: Update for Qt 5.12.5

- modules/LuneOS/Components/Tweak.qml
- test/imports/LuneOS/Service/LunaService.qml
> luneos-components: Rename Tweaks

- modules/QtQuick/Controls.2/LuneOS/Menu.qml
> QtQuickControls2.LuneOS: fix Menu component

- modules/LuneOS/Service/plugin/lunaserviceadapter.cpp
- modules/LuneOS/Service/plugin/plugin.pro
- test/imports/LuneOS/Service/LunaService.qml
> ACG: Migrate back to master branch

- modules/LuneOS/Components/UserAgent.qml
> UserAgent.qml: Update for Qt 5.15

- test/imports/LuneOS/Service/LunaService.qml
* Fix dummy calls to org.webosports.service.ipkg
* Add dummy call to launch com.palm.app.accounts
> LunaService.qml: Add dummy calls

- test/imports/Eos/Window/EosRect.qml
- test/imports/Eos/Window/EosRegion.qml
- test/imports/Eos/Window/WebOSWindow.qml
- test/imports/Eos/Window/qmldir
> stubs: add Eos.Window stub

- modules/LunaNext/Common/settingsadapter.cpp
- modules/LunaNext/Common/settingsadapter.h
- test/imports/LunaNext/Common/SettingsStub.js
> luneos-components: Remove compatDPI
